# Path to your oh-my-zsh installation.
export ZSH=$HOME/dotfiles/shell/oh-my-zsh
ZSH_THEME="bira"
plugins=(git)

source $ZSH/oh-my-zsh.sh

if [ -f ~/dotfiles/shell/commonrc.sh ]; then
    source ~/dotfiles/shell/commonrc.sh
fi

if [ -f ~/.bash_local ]; then
    source ~/.bash_local
fi
